### PR TITLE
feat: Removes path based patching. Adds anchor based.

### PR DESCRIPTION
**Pull request by jfyne**
Should help with extensions which mess with the DOM.

Refs:
 - https://github.com/jfyne/live/issues/28

### CODE REVIEW

**Comment by jfyne** [comment]
@AnaelBerrouet can you test this branch with your extensions?

**Comment by AnaelBerrouet** [comment]
> @AnaelBerrouet can you test this branch with your extensions?

Will pull today and test

**Comment by AnaelBerrouet** [comment]
Ran the test without branch changes again as sanity test, with extension that adds DOM elements and caused problems previously, as expected doesn't work. Then added the branch changes to the import and ran the buttons example successfully even with extension active. Awesome work!

**Comment by jfyne** [comment]
@AnaelBerrouet thanks for your help testing!

**Pull request merged**
