### PR TITLE
Add unmount handler

### PR DESCRIPTION
**Pull request by miko**
Follow-up to https://github.com/jfyne/live/discussions/57 - used Unmount (instead of disconnect) because it is the opposite of Mount.

### CODE REVIEW

**Comment by jfyne** [comment]
Hi thanks for the PR

Can you give me an example of what you will be using this for?

**Comment by miko** [comment]
No code yet, but:
- to show a number of users currently watching a webpage
- to release server resources (like cache, database connections etc) when no user is connected

**Comment by dmarko484** [comment]
I can also see this use case quite useful: "to show a number of users currently watching a webpage" . Technically, when this event is being issued? When the user closes the tab/page in browser? Or is there some other situation?

**Comment by miko** [comment]
> I can also see this use case quite useful: "to show a number of users currently watching a webpage" . Technically, when this event is being issued? When the user closes the tab/page in browser? Or is there some other situation?

When the websocket connection is terminated, so all of he above, plus network error (lost connection).

**Comment by aep** [comment]
shouldnt the unmount handler get the interface{} returned from the mount handler?

the clock example creates a go routine in the mount handler, and it would sound like a good idea to add a context to the returned object which can be called from unmount

```go
func mount(ctx context.Context, s live.Socket) (interface{}, error) {
   return NewResource(), nil
}

func unmount(s live.Socket, i interface{}) {
   FreeResource(i)
}


```

**Pull request merged**
